kind: pipeline
type: docker
name: nuxt-app-deploy

steps:
  - name: quality
    image: node:20-alpine
    commands:
      - npm install
      - npm run lint
      #- npm run typecheck

  - name: build-staging
    image: node:20-alpine
    commands:
      - npm install
      - npm run build:staging
    depends_on:
      - quality
    when:
      branch:
        - dev

  - name: build-production
    image: node:20-alpine
    commands:
      - npm install
      - npm run build:production
    depends_on:
      - quality
    when:
      branch:
        - main

  - name: deploy-staging
    image: alpine:3
    commands:
      - apk update && apk upgrade
      - apk add openssh bash rsync
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
      - printf "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
      - chmod 600 ~/.ssh/id_ed25519
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_ed25519
      - rsync -rav --quiet --exclude='.env' --exclude='node_modules' -e "ssh -p $STAGING_SSH_PORT" .output/ $STAGING_SSH_USER@$STAGING_SSH_HOST:$STAGING_PATH/
      - rsync -rav --quiet -e "ssh -p $STAGING_SSH_PORT" package.json package-lock.json $STAGING_SSH_USER@$STAGING_SSH_HOST:$STAGING_PATH/
      - ssh -p $STAGING_SSH_PORT $STAGING_SSH_USER@$STAGING_SSH_HOST "cd $STAGING_PATH && npm ci --production && pm2 restart nuxt-app || pm2 start --name nuxt-app node server/index.mjs"
    environment:
      SSH_PRIVATE_KEY:
        from_secret: staging_ssh_key
      STAGING_SSH_PORT:
        from_secret: staging_ssh_port
      STAGING_SSH_HOST:
        from_secret: staging_ssh_host
      STAGING_SSH_USER:
        from_secret: staging_ssh_user
      STAGING_PATH:
        from_secret: staging_path
    depends_on:
      - build-staging
    when:
      branch:
        - dev

  - name: deploy-production
    image: alpine:3
    commands:
      - apk update && apk upgrade
      - apk add openssh bash rsync
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
      - printf "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
      - chmod 600 ~/.ssh/id_ed25519
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_ed25519
      - rsync -rav --quiet --exclude='.env' --exclude='node_modules' -e "ssh -p $PRODUCTION_SSH_PORT" .output/ $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST:$PRODUCTION_PATH/
      - rsync -rav --quiet -e "ssh -p $PRODUCTION_SSH_PORT" package.json package-lock.json $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST:$PRODUCTION_PATH/
      - ssh -p $PRODUCTION_SSH_PORT $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST "cd $PRODUCTION_PATH && npm ci --production && pm2 restart nuxt-app || pm2 start --name nuxt-app node server/index.mjs"
    environment:
      SSH_PRIVATE_KEY:
        from_secret: production_ssh_key
      PRODUCTION_SSH_PORT:
        from_secret: production_ssh_port
      PRODUCTION_SSH_HOST:
        from_secret: production_ssh_host
      PRODUCTION_SSH_USER:
        from_secret: production_ssh_user
      PRODUCTION_PATH:
        from_secret: production_path
    depends_on:
      - build-production
    when:
      branch:
        - main

trigger:
  branch:
    - dev
    - main