export type { Platform } from './platform'
export type { Game } from './game'
export type { Serie } from './serie'
export type { Group, GroupsApiResponse } from './group'
export type { Chart, ChartsApiResponse } from './chart'
export type { ApiResponse, GamesApiResponse } from './api'